### ISSUE TITLE
incompatible with Android Studio Arctic Fox | 2020.3.1

### ISSUE THREAD

**Issue by thomas-p95** [springmonster/RestfulTool-Retrofit#1]

**Comment by thomas-p95** [comment]
hi @springmonster, can you update this plugin? thank you so much

**Comment by springmonster** [comment]
> hi @springmonster, can you update this plugin? thank you so much
Hi @tungpham6195 , you can check latest version 1.4, support Android Studio Arctic Fox | 2020.3.1
Thanks
